------=============================================================================================
------=============================================================================================
----* KINET PUBG Macro 
----* CREATED BY KINET 
----* Version: Script for All Mouse
----* Note: My script does not remove 100% recoil. it just helps you control the weapon more easily
------======================================================================================------
------======================================================================================------
------======================================================================================------

------********************************** INSTRUCTIONS ***************************************------

---- * First You need to Set ADS on HOLD (IN GAME SETTINGS) 

---- * You need to Hold 'Right Click' when you fire after activate gun's macro.

---- * CAPSLOCK = When you use SCOPE Then your keyboard CAPSLOCK light should be 'ON' Otherwise 'OFF' it.

------********************************** INSTRUCTIONS ***************************************------


------======================================================================================------
------======================================================================================------
------======================================================================================------

local recoil = true
local scopmode = true   	--- If you don't want use this function change value true to false
local scopmode_key = "capslock"

------======================================================================================------
------======================================================================================------
------======================================================================================------


------=============================================================================================------
---> FUNCTIONS
------=============================================================================================------
EnablePrimaryMouseButtonEvents(true);
function OnEvent(event, arg)
    if (event == "PROFILE_ACTIVATED") then
     OutputLogMessage("\n- - - - MACRO -> ACTIVE - - - -\n")
     OutputLogMessage("\n- - - - SCRIPT FOR ALL MOUSE CREATED BY KINET - - - -\n")
    elseif event == "PROFILE_DEACTIVATED" then
        ReleaseMouseButton(2)  
    end
   

   
 local RCm = 1
    local GG = 0
    RC_TABLE = {
            { x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 01*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 01*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 07*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 01*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 01*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 01*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 08*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 01*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 01*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 11*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 09*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
		{ x = 00*RCm,  y = 10*RCm },
} 
RC_COUNT = #RC_TABLE  
local LastIndex = 1 while recoil do if IsMouseButtonPressed(3) then while IsMouseButtonPressed(3) do if IsMouseButtonPressed(1) then if (LastIndex <= RC_COUNT) then i = LastIndex else i = 1 end while i <= RC_COUNT do MoveMouseRelative(0, RC_TABLE[i].y+4)Sleep(10) if not IsMouseButtonPressed(1) then break end  if not IsMouseButtonPressed(3) then break end  i = i + 1 end end end end while IsKeyLockOn(scopmode_key) and scopmode do if IsMouseButtonPressed(3) then while IsMouseButtonPressed(3) do if IsMouseButtonPressed(1) then if (LastIndex <= RC_COUNT) then i = LastIndex else i = 1 end while i <= RC_COUNT do MoveMouseRelative(0, RC_TABLE[i].y*2+4)Sleep(10) if not IsMouseButtonPressed(1) then break end  if not IsMouseButtonPressed(3) then break end  i = i + 1  end end end end end end end